image: docker:latest
stages:
- build
- release
variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: dockerci
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
services:
- docker:dind
before_script:
- apk update && apk add --no-cache git
- docker info
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
build:
  stage: build
  tags:
    - docker
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
release:
  stage: release
  tags:
    - docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
