image: docker:latest
stages:
- build
- release
variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: dockerci
services:
- docker:dind
before_script:
- apk update && apk add --no-cache git
- docker info
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
build:
  stage: build
  tags:
    - docker
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
release:
  stage: release
  tags:
    - docker
  script:
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

