image: docker:latest
stages:
- build
variables: 
  DOCKER_DRIVER: overlay
  DOCKER_USER: dockerci
services: 
- docker:dind
before_script:
- apk update && apk add --no-cache git
- docker info
job:
  stage: build
  tags:
    - docker
  script:
    - version=$(cat version)
    - echo $version
    - docker login -u $DOCKER_USER -p $CI_BUILD_TOKEN $CI_REGISTERY 
    - docker build --pull -t $CI_REGISTERY_IMAGE:latest .
    - docker build --pull -t $CI_REGISTERY_IMAGE:$version . 
    - docker push $CI_REGISTERY_IMAGE:latest
    - docker push $CI_REGISTERY_IMAGE:$version  
