image: docker:latest
stages:
- build
- release
variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: dockerci
services:
- docker:dind
before_script:
- apk update && apk add --no-cache git
- docker info
- version=$(cat version)
build:
  stage: build
  tags:
    - docker 
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
    - docker build --pull -t $CI_REGISTRY_IMAGE:$version .
release:
  stage: release
  tags:
    - docker
  before_script:
    - echo $version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$version
